### PR TITLE
Added WorldScript to Load configuration file.

### PR DESCRIPTION
**Pull request by KodyManharth**
#1 - Fixes this issue, or should by way of making the configuration take effect.

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
No need this pr, check https://github.com/azerothcore/skeleton-module/pull/4

**Comment by KodyManharth** [comment]
That pull request is from a different project. Not sure of it's relevance? 
The module was broken and giving me errors in the console related to missing configuration settings when I joined with a new character. 
This module seems to use (what may be older) manual inclusion of the config file in the install process as seen here: https://github.com/azerothcore/mod-starter-guild/blob/master/src/cmake/after_ws_install.cmake

There was no WorldScript in the code files to load the config. I went through several other modules and took the code from there. It was in all of them, which seemingly require the code to work.

This was also fixing an issue someone else has reported. #1

**Comment by BarbzYHOOL** [comment]
what winfi means is that the skeleton module is a template to use to fix other general modules  issues


I think that you didn't use the correct (more optimal) way to load configuration but I'm not sure

**Comment by milestorme** [comment]
Yeah I’m gunna finish cleaning this up this arvo

**Pull request merged**
